### ISSUE TITLE
Unable to parse file header

### ISSUE THREAD

**Issue by toto975** [Intervention/gif#13]
**Describe the bug**
I want to resize an animated Gif.
I decode the original gif into frame.
Then resize each frame.
Then add resized frame to a new gif.

**Code Example**
```
use Intervention\Gif\Decoder;
use Intervention\Gif\Builder;

$gif = Decoder::decode('my.gif');
$frames = $gif->getFrames();

if ($gif->isAnimated()) {
    $gifredim = Builder::canvas(width: 100, height: 100);
    foreach ($frames as $frame) {
        $gifredim->addFrame($frame); <======== Here is the bug
    }
    $data = $gifredim->encode();
    file_put_contents(Storage::disk(config('voyager.storage.disk'))->path('').$path.$filename.'_resize.'.$file->getClientOriginalExtension(),$data);
}
```
**Expected behavior**
Each frame must have a 'GIF89a' header.

When i `dump(file_get_contents('my.gif')`, i can see the 'GIF89a' header.
`b"GIF89a\x18\x01`

In the foreach loop, each frame is missing an header.
In the Intervention\Gif\Builder::addFrame function, when i `dump($source)`, i can't see the 'GIF89a' header

`b"! \vNETSCAPE2.0\x03\x01\x00\`

**Images**
I've tried with 3 differents animated gif, same error.

**Environment (please complete the following information):**
 - PHP Version: 8.2.4
 - OS: Windows 10
 - Package Version: 4.0.2

**Comment by olivervogel** [comment]
Thanks for reporting. I will look into this.

In the meantime, you can use [Intervention Image](https://github.com/Intervention/image/). This should work.

```php
$manager = ImageManager::withDriver($driver);
$image = $manager->read('my.gif');

if ($image->isAnimated()) {
    foreach ($image as $frame) {
        file_put_contents(
            $filename,
            (string) $manager
                ->create(100, 100)
                ->place($frame->toImage())
                ->toGif()
        );
    }
}

```

**Comment by olivervogel** [comment]
Your example will not work because `getFrames()` returns an array of `Intervention\Gif\FrameBlock` objects. However, these cannot be added via `addFrame` because this method currently only accepts raw GIF data or a path in the file system.

I recommend to go the way described in my previous comment.

**Comment by toto975** [comment]
I would like to use your solution, but I use another package which is locked to Intervention\Image 2.7
And i can't upgrade it for now.
So i can't use Intervention\Image 3.4.0 :-(

Have you a solution with Intervention\Gif ?

**Comment by olivervogel** [comment]
> Have you a solution with Intervention\Gif ?

Unfortunately not really, this package serves more as a substructure of `intervention/image`. For this reason the public API is not 100% polished.

**Comment by toto975** [comment]
Ok, thanks.
I will try to upgrade later and use your `intervention/image` solution.
